# -*- mode: ruby -*-
# vi: set ft=ruby :

# Versão da API do Vagrant
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
# This define how many virtual machines will be created:
N = 5
	(0..N).each do |i|
    	config.vm.define "vmcentos23#{i}" do |vmcentos|
		vmcentos.vm.box = "centos/7"
		# Define a versão da box utilizada pelo Vagrant:
		#vmcentos.vm.box_version = "10.4.0"
		# Define se o Vagrant vai buscar atualizaçoes da box utilizada. (true, false):
		vmcentos.vm.box_check_update = true
		#vmcentos.vm.box_url = "file:///home/ewerton/CentOS-7-x86_64-Minimal-1908.json"
		# Define o hostname da VM:
		vmcentos.vm.hostname = "vmcentos23#{i}"
		# Configuração da rede da VM - (IP fixo e em modo "bridge"):
		vmcentos.vm.network "public_network", bridge: "eno1", ip: "192.168.0.23#{i}"
		#vmcentos.vm.network "private_network", ip: "10.10.10.10"
		#vmcentos.vm.network "forwarded_port", guest: 80, host: 8080
		# Mensagem a ser exibida apos a máquina ser iniciada e quando a mesma for acessada via ssh:
		vmcentos.vm.post_up_message = "Infra As A Code - Vagrant in Action!"
        
		vmcentos.vm.provider "virtualbox" do |vmcentos|
		vmcentos.check_guest_additions = true
		vmcentos.gui = false
		# General 1/4 - Basic:
		vmcentos.customize ["modifyvm", :id, "--name", "vmcentos23#{i}"]
		# General 2/4 - Advanced:
		vmcentos.customize ["modifyvm", :id, "--clipboard", "disabled"]
		vmcentos.customize ["modifyvm", :id, "--draganddrop", "disabled"]
		# System 1/3 - Motherboard:
		vmcentos.customize ["modifyvm", :id, "--memory", "1024"]
		vmcentos.customize ["modifyvm", :id, "--pagefusion", "on"]
		vmcentos.customize ["modifyvm", :id, "--boot1", "disk"]
		vmcentos.customize ["modifyvm", :id, "--chipset", "piix3"]
		vmcentos.customize ["modifyvm", :id, "--mouse", "ps2"]
		vmcentos.customize ["modifyvm", :id, "--ioapic", "on"]
		vmcentos.customize ["modifyvm", :id, "--rtcuseutc", "on"]
		# System 2/3 - Processor:
		vmcentos.customize ["modifyvm", :id, "--cpus", "2"]
		vmcentos.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
		vmcentos.customize ["modifyvm", :id, "--pae", "on"]
		# System 3/3 - Acceleration:
		vmcentos.customize ["modifyvm", :id, "--paravirtprovider", "default"]
		vmcentos.customize ["modifyvm", :id, "--nestedpaging", "on"]
		# Display 1/3 - Screen:
		vmcentos.customize ["modifyvm", :id, "--vram", "8"]
		vmcentos.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
		# Audio 1/1 - Audio:
		vmcentos.customize ["modifyvm", :id, "--audio", "none"]
		# USB 1/1 - USB:
		vmcentos.customize ["modifyvm", :id, "--usb", "off"]
		vmcentos.customize ["modifyvm", :id, "--usbehci", "off"]
		end
		end
	end
end
